README.rst, stingray/lightcurve.py, stingray/powerspectrum.py, tests/test_lightcurve.py, tests/test_powerspectrum.py
I wasn't happy with the way you could pass either arrays for time stamps and counts to the __init__ of Powerspectrum or a Lightcurve object, so I've removed the first opportunity and made it required to put in a Lightcurve object (it adds one line to anyone's code to do this, but makes handling within Powerspectrum much easier). 
I've also fixed some bugs in the AveragedPowerspectrum class and added a bunch of tests for both lightcurve.py and powerspectrum.py.
This should hopefully be the last structural change to Lightcurve and Powerspectrum, so that we can now build upon those two classes for further development.
Please review and comment and/or merge if you get a chance.
=> Powerspectrum requires lc object

stingray/__init__.py
fix absolute import deprecation for python 3 and 2 compatibility:
instead of  `from powerspectrum import *`, uses  `from stingray.powerspectrum import *`
=> Fix import call on `__init__.py`

tests/test_powerspectrum.py
As the title says. `__defaults__` works on both python2.7.x and python3.x.
=> Uses atribute `__defaults__` instead of `func_defaults` for python 2 and 3 compatibility

stingray/lightcurve.py, tests/test_lightcurve.py
I wrote a small fix that allows for inputting count rates (counts/second) into the Lightcurve class definition instead of counts/bin as is the default now. All it does is add a bool keyword `input_counts` that is True by default (input counts/bin). Setting this keyword to False implies that the array in `counts` is in units of counts/second.
Pull request includes changes to documentation and a test.
=> Allow for count rates as input to Lightcurve class

stingray/utils.py, tests/test_lightcurve.py, tests/test_utils.py
As pointed out in issue #19, the current implementation of rebinning sometimes returns arrays with different lengths for the rebinned time/counts or frequencies/powers. This is a bug in the way the time and frequency arrays are constructed in the `rebin_data` function in `utils.py`. 
I've re-defined the way the time and frequency bins are calculated in a way that should fix this bug.
=> Bug fix for rebinning

stingray/powerspectrum.py
With these changes, I address Issue #32. The changes done until now eliminate assumptions on the fourier transform frequencies, and ask `scipy` to specify them.
=> Treat frequencies for any number of bins

stingray/lightcurve.py, stingray/powerspectrum.py
Change calls to `print` into a log. I also propose the following call to logging: `logging.info("method/class: message")`
```
logging.info("make_lightcurve: lc.counts: {}".format(lc.counts)"
```
This addresses Issue #35
=> Use logging and warnings instead of print

stingray/powerspectrum.py
Fixed #54. Build now succeeding.
It is a blockage in setting up of readthedocs.
=> Fix docstring of AveragedPowerspectrum for sphinx build

stingray/powerspectrum.py, stingray/tests/test_powerspectrum.py
As referenced in pull request #46, `classical_signififances` should return a numpy array instead of a zip object, the latter of which causes incompatibilities between Python2 and Python3. This patch should fix that problem.
=> classical_significances now returns numpy array instead of zip object

appveyor.yml
This PR adds necessary file(s) for starting CI based builds over [AppVeyor](https://ci.appveyor.com/projects). AppVeyor helps ensure that the code is _really_ OS independent by testing it over a Windows based platform.
The latest build on my fork can be seen here - https://ci.appveyor.com/project/OrkoHunter/stingray
@dhuppenkothen @matteobachetti Please tell me when you add a hook on the AppVeyor site. I'll refresh the PR and we'll watch the build and merge.
=> Activate Appveyor CI

README.rst
Minor change in README.rst which corrects the file path
required for building and viewing the documentation.
**"doc/" --> "docs/"**
=> Corrected the file path for the documentation directory in README

stingray/utils.py
On line 74, the code tries to access the shape attribute
of the iterable, y. If y happens to be a list, it will
result in an Attribute error. Thus, code converting y into a
numpy array beforehand was added.
=> stingray/utils: Minor fix to avoid attribute error

.travis.yml, setup.py
@dhuppenkothen We're getting build failure for Py 3.5
```
Traceback (most recent call last):
File "setup.py", line 25, in <module>
conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/122)
=> [WIP] Add Python 3.5 in Travis build

stingray/crossspectrum.py
This avoids crashes due to scipy refusing to cast longdoubles into floats (E.g. `cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'` ).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/130)
=> When rebinning logarithmically cross power spectra, use simple floats

stingray/__init__.py, stingray/covariancespectrum.py, stingray/tests/test_covariancespectrum.py
Currently, this PR adds a basic functionality to create a covariance spectra for full range of event list.
To do :
A working example :-
```python
>>> event_list = np.array([[1, 2],
[1, 4],
[1, 8],
[3, 6],
[3, 1],
[4, 2],
[4, 4],
[4, 6],
[4, 7],
[4, 5],
[4, 9],
[5, 1],
[5, 6],
[5, 7],
[5, 9],
[5, 3],
[5, 8],
[6, 1],
[6, 3],
[7, 3],
[7, 4],
[7, 5],
[7, 7],
[8, 8],
[9, 2],
[9, 5],
[9, 9]])
>>> c = Covariancespectrum(event_list, 1)
>>> c.energy_covar
{1.5: -0.2857142857142857,
2.5: 0.14285714285714285,
3.5: 0.0,
4.5: 0.14285714285714285,
5.5: 0.2857142857142857,
6.5: 0.2857142857142857,
7.5: 0.5714285714285714,
8.5: 0.46428571428571425}
```
The format and technique are all open to discussion. I've ignored a little of pep8, which I intend to fix soon.
---
This change is [<img …
=> Add covariance spectra

stingray/crossspectrum.py, stingray/lightcurve.py, stingray/tests/test_lightcurve.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_utils.py, stingray/utils.py
Fixes #82 
the `rebin_data()`  method now consistently  returns the mid-points of combined bins.
Both for Lightcurves and Powerspectra.
- renamed `Lightcurve.rebin_lightcurve` to `Lightcurve.rebin()` (to be consistent with `Powerspectrum.rebin`).
- Fixes `Powerspectrum.rebin()` legacy code when we were still using the 0th frequency.
- Fixes test in `test_powerspectrum` where we test if `freq[0]==df`, which is not True for binned Powerspectra.
- Merge master branch changes into this
Reviews are welcome ^_^
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/140)
=> Fix the `rebin_data()` method

stingray/crossspectrum.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py
Fixes #151 
Quickfix for `AveragedPowerspectrum.rebin()` which was broken.
Also add a simple test for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/153)
=> Bugfix AveragedPowerspectrum rebin

.travis.yml, docs/conf.py
`distutils.config` was moved to a separate module named `configparser ` in Python 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/160)
=> Fix sphinx-build failure with Python 3 and coveralls failure

stingray/lightcurve.py
Part of the issues related to the warnings in travis build for the sphinx docs.
See #166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/167)
=> Fix un-escaped underscores in reST

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
Hi,
This PR addresses a part of [issue-90](https://github.com/StingraySoftware/stingray/issues/90). It is to support bin edges, with `bin_lo` containing lower time stamps of all bins and `bin_hi` the corresponding higher ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/170)
=> added bin edges support

stingray/simulator/models.py, stingray/simulator/simulator.py, stingray/simulator/tests/test_simulator.py
1. Support for astropy.modeling: now an user can choose to simulate one of the models defined in astropy.modeling.models, a library function that uses the astropy.modeling.Model syntax (see point 2 below), an ex-novo user defined astropy.modeling.Model function or an arbitrary combination of these.
Example:
`smoothbknpo = models.SmoothBrokenPowerLaw(norm=1., gamma_low=1., gamma_high=2., break_freq=1.)`
`lorentzian = models.GeneralizedLorentz1D(x_0=10, fwhm=1., value=10., power_coeff=2.)`
`myModel = smoothbknpo + lorentzian`
`sim = simulator.Simulator(N=50000, mean=30000., dt=0.01)`
`lc = sim.simulate(myModel)`
2. Refactored generalised Lorentzian and smooth broken power law functions (in stingray.simulator.models) using astropy.modeling.Model class
3. Code cleanup
---
This change is [<img …
=> Adding support for astropy.modeling.models

.travis.yml
Return from Travis after all compulsory tests have returned, don't wait for tests allowed to fail. Rearrange so that tests allowed to fail are last
[EDIT: FYI: it's working. In one of the two Travis CI checks below, the tick appeared as soon as the "important" builds were done, even if the failure-allowed ones were still running. This saves some time.]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/190)
=> Use fast_finish and some refactoring

stingray/crossspectrum.py, stingray/events.py, stingray/lightcurve.py, stingray/tests/test_lightcurve.py, stingray/varenergyspectrum.py
In real-life applications, when loading observations from different instruments, the reference MJD will always be needed. It is also useful in order to save the light curves with a clear time reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/197)
=> Add MJDREF information

stingray/lightcurve.py
The confidence intervals, to be transformed in a proxy of the uncertainty, need the "mean" to be subtracted.
As they were calculated, these errors were just a number very close to the mean.
E.g. 
```In [1]: from astropy.stats import poisson_conf_interval
In [2]: import numpy as np
In [3]: a = np.random.poisson(1000, 10)
In [4]: m, M = poisson_conf_interval(a, sigma=1)
In [5]: poisson_std = np.sqrt(a)
In [7]: m, M, poisson_std
Out[7]: 
(array([ 1003.81304612,  1017.59629651,  1003.81304612,   921.14550276,
1009.71997522,  1025.47308807,   997.90638693,   937.87123517,
957.55162961,  1030.39631923]),
array([ 1068.18695388,  1082.40370349,  1068.18695388,   982.85449724,
1074.28002478,  1090.52691193,  1062.09361307,  1000.12876483,
1020.44837039,  1095.60368077]),
array([ 32.18695388, …
```
=> Correct Poissonian errors on light curves

.travis.yml, docs/simulator.rst, stingray/modeling/scripts.py, stingray/varenergyspectrum.py
Closes #194 
Astropy now doesn't bundle Pytest, and the behavior of newer versions of Pytest is a little different (for example it does doctests). These two small fixes should settle it.
BTW, this forces us to be thorough also when we write documentation. All doctest-formatted tests will run :)
=> Fix failing tests in Astropy development version

stingray/tests/test_varenergyspectrum.py
There was a missed pha -> energy on the tests making the master build fail. this fixes it.
=> Fix test_varenergyspectrum: Change pha to energy following PR #199

stingray/simulator/simulator.py
I wanted to simulate light-curves with floating point spectral indices and found that it was not possible due to the `isinstance(args[0], numbers.Integral)` check in the `Simulator.simulate()` method. 
Since the `simulate_power_law()` method can handle floats, I added floats to the accepted data types.
Cheers, Max
=> Added check for float in Simulator.simulate()

stingray/lightcurve.py
I've changed the implementation and reduced the time complexity from O(N^2) to an O( N Log(N) ). The problem in the old implementation is that it sorts the lc.time and then searches for the consequent count for each new time. The new implementation uses the zip function that zips the arrays time, counts, count_err. What's good about the zip function is that after we sort the time array, it moves the zipped arrays accordingly, and that is exactly what we are trying to do.
=> Lightcurve's sort method speed-up

.travis.yml, stingray/pulse/pulsar.py, stingray/pulse/search.py, stingray/pulse/tests/test_pulse.py, stingray/pulse/tests/test_search.py, stingray/utils.py
The basic functionality for pulsation searches with the Epoch Folding algorithm and the Z^2_n statistics is implemented. 
It also implements a way to use simple thresholding of peaks in the periodogram.
To speed up the processing, I added a dependency on the `numba` library. I made it in such a way that if it is not installed the processing happens anyway, just much slower. On travis, all tests but one run without it.
The full fit of the peak with a `sinc` function à la Leahy+87, initially planned for this PR, will be implemented later.
=> Functions to search for pulsations, using epoch folding and/or Z^2_n stat

stingray/tests/test_varenergyspectrum.py, stingray/varenergyspectrum.py
Avoid loop crash if some CrossSpectra is wrong in LagEnergySpectrum or RmsEnergySpectrum, just added try catch for avoid "Mean count rate is <= 0. Something went wrong" assertion if some of the lightcurves of the interval are empty after being processed inside AveragedCrossspectrum.
=> LagEnergySpectrum and RmsEnergySpectrum bug fixing

stingray/events.py, stingray/simulator/base.py, stingray/simulator/simulator.py, stingray/simulator/tests/test_base.py, stingray/tests/test_events.py
Move the core of the acceptance-rejection method to the `simulator` module where it belongs.
Comment for reviewers: the changes to `simulator.py` are only PEP8-related!
=> Simulation of event lists from lightcurve moved to simulator submodule

stingray/crossspectrum.py, stingray/lightcurve.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_lightcurve.py, stingray/tests/test_powerspectrum.py, stingray/utils.py
Closes #150, reboots #233
~Two changes here~:
+ `rebin_log` returns a *spectrum instance, consistently with `rebin`
+ `rebin` now accept a rebin _factor_ instead of just the new resolution, both in `Lightcurve` and in {cross,power} spectra
EDIT: Actually things turned out to be far more complicated than this. Tests did not contain the case of calculating lags from rebinned cross spectra. Well, this was were things went terribly wrong: `coherence` wanted some power spectra, that needed to be binned exactly like the main spectrum. So, in the end, I did this:
+ In `{Averaged,}Crossspectrum`, calculate the cross spectrum _and_ the power spectra of the input light curves. This operation (`_make_auxil_spectra`) was put into an `if lc1 is not lc2` condition so that this doesn't become an …
=> rebin_log returns a Powerspectrum/Crossspectrum instance, allows rebin factor

stingray/gti.py, stingray/lightcurve.py, stingray/tests/test_gti.py, stingray/tests/test_lightcurve.py, stingray/utils.py
This comes from the need of calculating excess variance in regular chunks of light curves (AGN stuff).
I made it a little more generic, so that people can pass their own statistics to be calculated on the light curve chunks. Excess variance is the example in `test_analyze_lc_chunks_fvar`.
Plus I fixed Fvar, that was missing a square root (screaming face)
EDIT: Plus I allowed to use rolling windows (steps of fractions of `chunk_length` in starting times), which involved also modifying slightly `bin_intervals_from_gtis`.
EDIT 2: Notebook here: https://github.com/StingraySoftware/notebooks/pull/16
=> Bugfix + Add method to analyze regular chunks of a lightcurve with generic functions

.travis.yml, stingray/pulse/tests/test_search.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_varenergyspectrum.py
+ Cleanup .travis-ci.yml from Python and bumpy versions unsupported by Astropy
+ Speedup some test suites that were above 30 s each (I leave test_parameterestimation to @dhuppenkothen's next PR)
=> Speedup tests and cleanup travis builds

stingray/events.py
Running following code,
Produced Type Error,
This PR fixes this. j in lc.counts has to be int to produce required number of array elements.
=> Fixes Type Error in EventList.from_lc

.travis.yml, appveyor.yml, stingray/lightcurve.py, stingray/tests/test_lightcurve.py, stingray/utils.py
This has been triggered by Issue 282 in DAVE. That's probably not an issue, but I did find a mistake in the error bar calculation for the unnormalized excess variance. I took the chance to document the function better and to allow both normalized and unnormalized excess variance.
ADD: During tests of this new functionality, I discovered a bug in the slice operation with light curves, where GTIs were forgotten. I fixed this and tested it properly.
=> Fix excess variance error bar; allow normalized excess variance; fix GTI behavior during slicing

stingray/crossspectrum.py
As things are defined for now, time lags are calculated correctly only when powers are unnormalized.
`_normalize_powerspectrum`, in fact, defines power as the real part of `unnorm_power`. Which is correct in principle if one is interested in the cospectrum, but has the side effect to make lag calculation impossible.
`unnorm_powers`, instead, remains a complex number and can be used to calculate lags. Hence this small modification that should always work.
=> Use unnorm_power to calculate lags

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
== operator is overloaded to compare two lightcurves. For now, only condition for two lc's to be equal is that their times and count arrays are equal. I think it covers all other properties since they are calculated from these two basic inputs to lightcurve.
=> == operator for lc

stingray/simulator/simulator.py
The `random_state` variable of the Simulator.simulate method was shown as `seed` in the help text.
=> Fixed variable name

stingray/crossspectrum.py
Using `power`, often the imaginary part is thrown away, so lags are always 2n\pi.
=> Bugfix: Use unnorm_power for time lags, _everywhere_

stingray/events.py, stingray/gti.py, stingray/modeling/parameterestimation.py, stingray/pulse/pulsar.py, stingray/simulator/base.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py
While running a few large computations, I realized that the builtin `max()` was taking 90% of the time in certain operations. 
I substituted `np.max` in all operations that involve numpy arrays.
=> Substitute max() with np.max, and same for min, everywhere

.travis.yml, stingray/bispectrum.py, stingray/covariancespectrum.py, stingray/io.py, stingray/lightcurve.py, stingray/modeling/parameterestimation.py, stingray/modeling/posterior.py, stingray/modeling/scripts.py, stingray/simulator/simulator.py
~~This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.~~
Some fixes were needed to make the new version of numpydoc happy.
I've also removed the travis job to test against astropy dev on python 2.7. We don't support that version any more, so that build will always fail.
=> Update astropy-helpers to v2.0.2 and fixes to the docstrings

.travis.yml, appveyor.yml
We'll do some automated PRs for these sometimes soonish, but I did them here now while I was already around.
With this, you can use the custom tags in commit messages implemented in ci-helpers, such as ``[docs only]`` and ``[skip travis]``. I suppose it will be quite useful as full build currently runs for over 4 hours...
=> Updating the usage of ci-helpers

stingray/lightcurve.py, stingray/tests/test_lightcurve.py, stingray/utils.py
This change in the methods allows to add an offset to the baseline calculated by `baseline_als`, so that it aligns with the mean of the light curve.
I changed the method in `utils.py` and its usage in `Lightcurve.baseline()`
=> Add offset correction to baseline in light curve

stingray/pulse/search.py, stingray/pulse/tests/test_search.py
@ricardovb reported on an error arising when frequencies and fdots are `numpy.float128`s. 
https://github.com/StingraySoftware/HENDRICS/issues/25
The error is actually due to Stingray, and this PR fixes it.
It should be pretty quick to review.
=> Fix issues with numpy.float128 frequencies and fdots

appveyor.yml, stingray/events.py, stingray/gti.py, stingray/lightcurve.py, stingray/pulse/search.py, stingray/pulse/tests/test_search.py, stingray/tests/test_events.py, stingray/tests/test_gti.py, stingray/tests/test_lightcurve.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_varenergyspectrum.py, stingray/utils.py, stingray/varenergyspectrum.py
This speeds up considerably the light curve creation from events when datasets are large, in three ways:
1. Using `np.bincount` instead of `np.histogram`. Resolves #252
2. Using a jit-compiled function to create GTI masks with a single loop over the time series, instead of the existing, purely pythonic one that used multiple filters on the full dataset for each GTI. Falls back to the old implementation if numba is not installed.
3. Using a lookup table in the calculation of `poisson_conf_interval`. The speedup is HUGE. Two orders of magnitude at least, on large datasets. 
EDIT: Note that `np.bincount` is slower when datasets are small. However, it seems like a good tradeoff. If you think that a use case might be creating a million small light curves, we could think of letting the user …
=> Speedup lc from events

stingray/covariancespectrum.py, stingray/modeling/posterior.py, stingray/tests/test_covariancespectrum.py
I've written a new implementation of the `Covariancespectrum` class in response to Issue #262 to add the capability to include light curves instead of event files. I tried with the original implementation, but the changes touched so many parts that it was easier to just write it from scratch. On the plus side, the code has fewer duplications.
The tests pass, but I get a lot of warnings about the excess variance being <0, so I'd appreciate someone with more knowledge of covariance spectra to take a look and hunt for bugs in the implementation (especially the parts that actually calculate the covariance etc).
=> New version of covariance spectrum class

stingray/crossspectrum.py, stingray/tests/test_crossspectrum.py, stingray/utils.py
This should fix the issue whereby the `rebin_data_log` in `utils.py` casts complex numbers to real ones, which means we loose the imaginary parts of the cross spectrum when rebinning. 
It now computes the real and imaginary parts of the rebinned cross spectrum separately and combines them back in the end into a set of complex values.
=> Fixed rebinning issues for complex numbers

stingray/modeling/tests/test_parameterestimation.py
more than 20 mins for each test is a lot. With this PR, I'm investigating the possibilities to decrease the time of execution of modeling tests. 
This first commit speeds up the tests by a ~full hour in total if sampling is not involved.
=> [WIP] Speed up some tests on lrt, highest outlier, etc.

stingray/gti.py, stingray/tests/test_gti.py
There was a bug that made the GTIs incorrect when using `numba` and specifying a "safe interval", a mechanism that is not often used, but useful and recommended in missions with frequent orbital gaps like NuSTAR where close to the GTI boundaries there might be activity flares or drops in the count rate.
Now it should be fixed.
=> Fix the mechanism of safe intervals in create_gti_mask

stingray/tests/test_varenergyspectrum.py, stingray/varenergyspectrum.py
The error bar in the rms spectrum was evidently wrong, because it was assuming the _power_ instead of the _power error_ in the squared sum.
Now it should be correct.
=> Fix rms error

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
This fix should solve #280, I hope. If GTIs are present, it will rebin each segment separately, and then combine the outputs into one new rebinned light curve.
=> Fixed bug where GTIs were not taken into account correctly in rebinning light curves

stingray/lightcurve.py
Tiny bug fix in `Lightcurve.truncate`: `truncate_by_time()` will fail if the time chosen to truncate at does *not* exactly match one of the time stamps of the light curve. I think that shouldn't be a necessary requirement: we should be able to truncate at whatever time we want, and it'll just find the nearest index.
Because our time arrays should be strictly sorted, `np.searchsorted()` is the better alternative here, since unlike `where()`, it doesn't require an exact match of the time indices. Hence the change in this PR.
=> Changed np.where to np.searchsorted in truncate method

stingray/gti.py, stingray/lightcurve.py, stingray/tests/test_gti.py, stingray/tests/test_lightcurve.py
Should fix issue #257, if I understood it correctly.
=> warning about unequal bin sizes now works correctly when GTIs are loaded

stingray/powerspectrum.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_utils.py, stingray/utils.py
I realized it wasn't possible to run the method `classical_significances` on log-binned periodograms, because it expected `self.m` to be a single integer, rather than a `numpy.ndarray`. 
In the process of enabling that functionality, I discovered a bug in the way `self.m` was calculated for the log-binned periodogram and fixed that, too.
=> Can now run classical_significances on log-binned periodograms

stingray/gti.py, stingray/lightcurve.py, stingray/tests/test_lightcurve.py
In issue #299, I've discussed that Lightcurve does not support Numpy integers like `int64`. This is a simple fix for that.
Another issue is with slicing. If `new_lc = lc[:]` is run, the length of Lightcurve counts reduces by half. Since I am not an astronomer, I am not familiar with 'Good Time Intervals' and 'Time Resolution'. So I would need help to fix the second problem.
**Needs discussion**: If we could create a `copy()` function so that the package provides more options other than slicing.
=> Support for Numpy integers and fixed slicing

stingray/gti.py, stingray/lightcurve.py, stingray/tests/test_lightcurve.py
`sort()` currently sorts only by counts. This is great, but it's not what I expected for a time series (I expected it to sort by time). It also turns out there are some issues that appear when the time bins are out of order. 
This PR should fix those issues, and implements `sort()` as sorting by time bin, and `sort_counts()` to sort by counts.
=> Fixed behaviour of sort

stingray/tests/test_lightcurve.py, stingray/utils.py
Resolves #292, throws a warning when data points are too few to perform offset correction with some precision.
=> Fix offset correction error

setup.cfg, stingray/gti.py, stingray/pulse/modeling.py, stingray/pulse/pulsar.py, stingray/pulse/search.py, stingray/pulse/tests/test_modeling.py, stingray/pulse/tests/test_pulse.py, stingray/pulse/tests/test_search.py, stingray/tests/test_crossspectrum.py
+ Solve a number of problems in the calculations of pulse arrival times
+ Give a choice over fitting methods (still no maximum likelihood)
+ Plot diagnostic information if needed
All the relevant changes are under `pulse/`. The rest is just a mixed-up PEP8 cleanup (sorry about that)
See https://github.com/StingraySoftware/notebooks/pull/30 to see the functions in action
Also, resolves #314, resolves #317
=> Make TOA calculation more robust

MANIFEST.in
The absence of LICENSE in the manifest is blocking conda builds
=> Add LICENSE to Manifest.in

stingray/crossspectrum.py
This PR introduces new parameter `amplitude` in `Crosspectrum` class. A user can now choose if the person wants just the real component or the amplitude of the cross spectrum.
Instead of passing it from one function to another function, I added `self.amplitude` to store user's choice.
**Usage:**
=> Added new parameter in cross spectrum class

stingray/powerspectrum.py
This class doesn't call `__init__` of its super class `AveragedPowerspectrum`. This PR resolves the problem.
=> Fix DynamicalPowerspectrum

stingray/io.py, stingray/powerspectrum.py, stingray/tests/test_powerspectrum.py
I just loaded some data using `load_events_and_gtis` and was *really* confused when I did `print()` on the output and it told me that I had an object of type `stingray.io._empty`, because it made me think that the function had failed to actually extract some data.
I understand where the name `_empty` comes from, but it's a really confusing one for a user-facing function, so I've given it a slightly more descriptive name.
=> refactor `_empty` into `EvtData`

.travis.yml, appveyor.yml, stingray/gti.py, stingray/modeling/scripts.py, stingray/modeling/tests/test_parameterestimation.py, stingray/modeling/tests/test_scripts.py, stingray/pulse/pulsar.py, stingray/simulator/simulator.py, stingray/simulator/transfer.py, stingray/tests/test_spectroscopy.py
I suppose this should get rid of most of the travis failures in the other PR (#377), but given that there are other deprecation warnings coming from upstream packages I think it makes sense to deal with them separately from the helpers update.
I highly recommend to enable `enable_deprecations_as_exceptions()` in conftest.py to pick up these deprecations as early as possible.
=> Fix deprecated numpy usage to avoid warnings

.travis.yml
@matteobachetti - I expect this to fix the egg build.
Keeping the language minimal has the advantage of having faster installs and it shouldn't matter as we use conda and pip to install the dependencies anyway. I expect that even the latex and dvipng install can be removed, but I haven't touched those.
=> Fixing egg build and removing remaining python 2.7 build

.travis.yml, setup.cfg, stingray/crossspectrum.py, stingray/lightcurve.py, stingray/pulse/search.py, stingray/tests/test_covariancespectrum.py, stingray/tests/test_crosscorrelation.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_io.py, stingray/tests/test_lightcurve.py
The current behavior is very strict: if light curves have a different tseg, `AveragedCrossspectrum` and the such will fail. This is probably an overkill.
The case in StingraySoftware/HENDRICS#52 is clear: the data have different GTIs and tseg is different. However, this is accounted for more than sufficiently by the `cross_gti` operations a few lines below the tseg check. If the light curve has no compatible gtis, everything will fail anyway. If GTIs have common intervals, the averaged cross spectrum will be calculated.
So, here I propose to change the `ValueError` into a `simon` warning, and let the subsequent GTI checks do the rest.
Additionally, `Lightcurve()._apply_gtis()` now also updates `tseg`. This seemed appropriate to do.
And `make_lightcurve` sorts the input array before …
=> Should fix the problem when tseg is different in light curves

stingray/gti.py, stingray/pulse/pulsar.py, stingray/tests/test_gti.py, stingray/utils.py
A missing bit of information in the Z2 statistics. We have the number of summed spectra in the PDS detection level, why not adding it to Z2 :)
=> Add n_summed_spectra to Z2n stats

stingray/pulse/pulsar.py
This modification is needed when correcting event times by small amounts (e.g. in the NuSTAR temperature correction), because the orbital correction uses interp1d and even a microsecond out of boundaries can raise exceptions in the strict mode. 
So, here I use fill_value="extrapolate" from interp1d in the orbital correction, and if out of bounds, I let the user decide if it's appropriate with a detailed warning. If out by a few seconds, it might be a minor issue.
=> Warn when extrapolating outside range in orbital correction

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
I keep running into the situation where I need to split light curves along data gaps, i.e. make a light curve of a contiguous light segment before a gap and a contiguous segment after a gap. I'm probably not the only one, so I wrote a method for `Lightcurve` that can do this.
Comments welcome! :)
=> New feature! Added lightcurve splitting

docs/intro.txt
Fixes #396 
The index page looks like this:
=> fix aspect ratio of logo

stingray/modeling/parameterestimation.py
In  a new version of `emcee` the keyword `iterations` no longer exists. I've replaced it with the length of the Markov chain, which should work. This should fix the Travis errors in #397, I think.
=> Fixed usage of deprecated iterations keyword in emcee

stingray/simulator/simulator.py
This should fix a bug in the `simulate_powerspectrum` method of the `Simulator` class. This took the PSD itself and multiplied it with a unit random normal variate, which is wrong, since the variance of the Fourier amplitudes should be scaled by `sqrt(P)`, rather than `P`. 
This fixes this errors, and also removes factors of two from the other cases, which should do nothing anyway, and this way it's all internally consistent.
=> Fixed bug in simulating light curves from PSDs given as arrays

.travis.yml, ah_bootstrap.py, stingray/conftest.py
This is an automated update of the astropy-helpers submodule to v3.2.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.2.1/CHANGES.rst). 
We've also noticed that you likely used the astropy package template in the past for your package and that your conftest.py file is now out of date and imports pytest plugins from astropy:
```python
from astropy.tests.pytest_plugins import *
```
This astropy sub-package has been removed, so your tests will likely be failing now that astropy v3.2 has been released. This PR therefore fixes this import by checking the astropy version and adjusting the import as needed.
We also wanted to …
=> Update astropy-helpers to v3.2.1

stingray/pulse/tests/test_search.py, stingray/tests/test_gti.py
This fix addresses https://github.com/twongCMU/stingray/issues/1 in which the some unit tests fail under pytest 5.0.0. This version changed an exception to only show the exception type and not the custom text; that info is in e.value now.
=> Have tests inspect an exception's e.value instead of just e as pytest 5.0.0 changed its behavior

stingray/powerspectrum.py
Resolves #420 
Considering the second return value is the output of `_compute_rms` function, I just copied the docstring. that's it!
cc @matteobachetti
=> Fix compute_rms doc in `powerspectrum.py`

.travis.yml, stingray/modeling/tests/test_posterior.py, stingray/tests/test_powerspectrum.py
Fix the issues related to the changes in the modeling interface in Astropy's 4.0 version. Some failures due to similar problems in the PINT dependency are expected, _only_ in the pulsar tests (anything else should be investigated and solved). 
Resolve #448
=> Fix numpy astropy issues

README.rst, docs/install.rst
Because people keep asking me how to run the tests if they've installed through pip and conda, I've added a couple of lines to the readme with a way to do that.
=> Added some alternative routes to running the tests to readme

stingray/crossspectrum.py, stingray/deadtime/fad.py, stingray/modeling/parameterestimation.py, stingray/tests/test_crossspectrum.py, stingray/varenergyspectrum.py
In the course of implementing normalizations for the FAD, I discovered a bug in the method that calculates normalizations: ```meanrate = np.sqrt((self.nphots1 * self.nphots2) / tseg)``` (wrong!) is not the same as ```meanrate = np.sqrt((self.nphots1 * self.nphots2)) / tseg```. 
The latter leads to a normalization where the PSD of white noise corresponds to 2 * the mean count rate, which I think should be right?
After fixing that, I gave `calculate_FAD_correction` the same `norm` keyword that `Crossspectrum` and `Powerspectrum` have, and normalized the Fourier products for each segment after deadtime correction.
=> Normalizations in FAD + bug fix in absolute rms normalization

.gitignore, .travis.yml, stingray/lightcurve.py, stingray/tests/test_lightcurve.py
- Implements `to_lightkurve` and `from_lightkurve` so as to provide connection to lightkurve package. 
- Modify .gitignore so as to include virtual environments and VSCode editor files
Fixes #429 
Closes #454
=> add support to lightkurve package

stingray/crossspectrum.py, stingray/deadtime/fad.py, stingray/lightcurve.py, stingray/powerspectrum.py, stingray/stats.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py, stingray/varenergyspectrum.py
I occasionally have light curves with fairly low counts and particularly variable count rates, so that when making an averaged PSD, I end up with segments that have no counts. 
Currently this always fails during the periodogram creation of that segment, but I think what it should really do is throw that segment away and continue without it.
=> Added if statement to skip over light curves with no counts

.travis.yml, stingray/crossspectrum.py, stingray/events.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py, stingray/utils.py
Event lists can now return a list (through a generator, so not all at once) of light curves from each of their GTIs.
This allows to use the existing machinery in `Average*spectrum` objects to iterate over these light curves and calculate the periodograms directly from events. 
This is *very* useful in very long observations of objects with high-frequency variability, where the number of bins in the complete light curve can easily reach hundreds of millions.
=> Accept Event Lists for periodograms

stingray/covariancespectrum.py, stingray/deadtime/fad.py, stingray/gti.py, stingray/io.py, stingray/pulse/pulsar.py, stingray/pulse/search.py, stingray/utils.py
Change all imports of `Iterable` from `collections` (deprecated) into imports from `collections.abc`
Resolve #475
=> Fix deprecated use of Iterable

stingray/deadtime/fad.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_utils.py, stingray/utils.py
Thanks to an email bug report by Tanuman Ghosh, I realized that we were not testing correctly for complex numbers in `rebin_data_log`. `isinstance(y, np.complex)` was in fact returning `False` for `np.complex64` objects.
This PR fixes this problem. Should be straightforward to review.
=> Fix binning of complex64

stingray/pulse/fftfit.py, stingray/pulse/pulsar.py, stingray/pulse/tests/test_pulse.py
We use the FFTFIT method to calculate pulsar TOAs.
This is based on the original paper by [Taylor 1992](https://ui.adsabs.harvard.edu/abs/1992RSPTA.341..117T/abstract), including error calculations (that, however, are not always super reliable).
The method is ~10 times faster and performs better than the previous implementation (tested on a bunch of pulsars, including the Crab, B1821-24A and B1937+21).
=> A much faster version of FFTFIT

stingray/powerspectrum.py, stingray/tests/test_powerspectrum.py
Fixes all `DynamicalPowerspectrum`-related issues. In particular:
- `DynamicalPowerspectrum.rebin_*` functions return a new object instead of changing the object itself
- The `sigmaclip` is eliminated from `DynamicalPowerspectrum.trace_maximum`
- Tests now verify that Issue #419 cannot be reproduced (it was a GTI problem, solved in previous PRs).
resolve #364, resolve #365, close #419
=> Fix dynpowspec

setup.cfg, stingray/events.py, stingray/lightcurve.py, stingray/tests/test_events.py, stingray/tests/test_lightcurve.py
And use TimeSeries for ascii I/O, and prepare for whatever comes next!
Resolve #506, resolve #470, and set the base to address #152
Also, adds some mission and instrument information as per #200, #90. We might want to add energy information too, as per #96
=> Roundtrip Eventlist and Lightcurve to astropy TimeSeries

stingray/events.py, stingray/lightcurve.py, stingray/tests/test_events.py, stingray/tests/test_lightcurve.py, stingray/utils.py
Until now, we were accepting `Time` objects. However, we just read the `value` attribute of it, which might have been in days, months, or any quantity accepted by `astropy.time.Time`. With this PR, we make sure `Lightcurve`s and `Eventlist`s maintain their `time` attribute as seconds from `mjdref`. If a `Time` object is passed, we calculate the seconds from `mjdref` (if `mjdref` is 0, we create one from the first time in the input array). If `time` is a `TimeDelta` or a `Quantity`, we make sure to convert them to seconds.
Closes #467
=> Use Astropy Time/TimeDelta/Quantity objects when initiating Lightcurves and Eventlists

stingray/lightcurve.py
There's a bug where applying `split` in `Lightcurve` changes the state of the GTIs of the original `Lightcurve` object it is being applied on. This is bad, because we're *returning* a list of new light curves, but have *changed* the GTIs of the original object to include the gaps we split on. This is probably not what we want. The easiest fix I could find is to give `split_by_gti` an optional extra `gti` keyword, in case the user (in this case `split`) wants to put in GTIs that are not already set in the `gti` keyword.
=> Fixes bug in `split` method in `Lightcurve`

stingray/crossspectrum.py
This is a one-line change, because I thought the warning about `pyfftw` wasn't very helpful to the user (I had to look up in the code why that warning happened), so I added the additional piece of information.
=> Minor change to make warning more descriptive

setup.cfg, stingray/crossspectrum.py, stingray/io.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_lightcurve.py, stingray/utils.py
These objects carry an array of spectra calculated in each segment, and when rebinning, these were also rebinned. This took a very long time, needlessly given the cs_all is itself not necessary. So, I added a save_all option to __init__.py that makes the cs_all garbage collected as soon as the calculation is done. The previous behavior is reinstated by using save_all when creating the spectrum.
Also, I silenced some more warnings here and there
Moar:
Close #315, close #313
=> Speedup rebin of Averaged Cross/Power spectra

stingray/bispectrum.py, stingray/crossspectrum.py, stingray/spectroscopy.py
to scipy.fft and the pyfftw equivalent. I checked the documentation, and thee relevant functions seem to be closely equivalent except for a new `norm` parameter that allows one to move the 1/n factor around. Given that nothing blew up in the tests, I'm thinking that the defaults are sensible for our purposes. :)
Resolves #535 and *might* address #310, but I haven't looked at that yet.
=> Updates FFT calls from legacy scipy.fftpack

stingray/__init__.py
I was sad that `EventList` is the only top-level stingray class that can't be important with `from stingray import EventList` but rather with `from stingray.events import EventList`, so I added `events` to the `__init__`. :)
=> Added events.py to top-level imports

README.rst, docs/install.rst
Reading through the documentation I realized that the documentation for running tests is inconsistent. The corrent way to run the tests is in the Readme, so this PR fixes the documentation.
Also fixed the readme to add `doctest-skip` step based on this comment: https://github.com/StingraySoftware/stingray/pull/553#discussion_r611552714
=> Fix test suite documentation to match with readme

README.rst, docs/.gitignore, docs/citing.rst, docs/conf.py
This updates citation guidance to request that folks cite a DOI.
It also queries Zenodo to pull a list of appropriate DOIs to cite, depending of the version of Stingray in use, and embeds that in the docs.
Why not hard-code that list? Primarily, because then docs for a given release wouldn't (easily) include its own DOI; you'd have to come back and edit it in after the release was made, thus changing the code to something subtly different from what the DOI is pointing to.
(It should also be possible to work around that issue by pre-reserving a DOI on Zenodo before the release, but doing things this way involves fewer manual steps to forget!)
=> Request citing DOIs

stingray/io.py, stingray/powerspectrum.py, stingray/stats.py, stingray/tests/test_stats.py
Resolve #492 
I added a bunch of utility functions in `stingray.stats`, including `amplitude_upper_limit` which calculates the maximum modulation amplitude that would produce the given value of power (in Leahy normalization) at the C confidence level, using material Vaughan+94 and Groth+75. This also works for the Z^2_n search, since the statistic is equivalent (e.g. Brazier+94) and corresponding to the noncentral chi squared distribution with 2n degrees of freedom, where n is either the number of summed power spectral bins (adjacent or harmonics, it's equivalent) or the "n" in Z^2_n.
Upper limits in Powerspectrum and AveragedPowerspectrum now available through
```
pds.modulation_upper_limit(fmin, fmax, confidence_level)
```
=> Upper limits on pulsations in periodograms

stingray/multitaper.py, stingray/tests/test_multitaper.py
These additions apply the multitapering concept to signals with uneven temporal sampling in order to estimate their power spectrum density. The Lomb (1976) Scargle (1982) periodogram used to calculate the PSD is rapidly computed using Astropy. 
This method is presented in Springford, Eadie & Thompson (2020).
Adds to #361 and #578, and replaces #583.
The newly added functionality is showcased at the end of [this](https://github.com/dhruv9vats/notebooks/blob/multitaper_periodogram/Multitaper/Multitaper_showcase.ipynb) notebook.
=> Extending the Multitapering concept to unevenly sampled time-series: Multitaper Lomb-Scargle

.github/workflows/ci_test.yml, docs/simulator.rst, stingray/sampledata.py, stingray/simulator/simulator.py, stingray/simulator/tests/test_simulator.py, stingray/tests/test_varenergyspectrum.py
There are a couple of issues in the current implementation of the simulator that are fixed with this PR:
* With default arguments, simulator produces a light curve of zeros
* The simulator generates light curves that are normalized by the empirical mean and variance before they are renormalized to the mean and fractional rms amplitude that's put in. This means that the resulting Fourier amplitudes are no longer Gaussian distributed, which might have weird effects downstream.
Changes in this simulator:
* add some `skip_checks=True` arguments to `Lightcurve` calls where we can be sure that the light curve is well behaved
* Removed default options from a number of arguments in the `Simulator.__init__`. I don't think we should allow people to run the Simulator with default values any more …
=> Fix normalization in simulator

stingray/simulator/base.py
From a private report:
```
In [9]: ev = EventList()
...: ev.simulate_times(lc)
...: ev.time
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-9-8e2de76e3da1> in <module>
1 ev = EventList()
----> 2 ev.simulate_times(lc)
3 ev.time
/soft/anaconda3/envs/3point8/lib/python3.8/site-packages/stingray/events.py in simulate_times(self, lc, use_spline, bin_time)
274                           DeprecationWarning)
275 
--> 276         self.time = simulate_times(lc, use_spline=use_spline)
277         self.gti = lc.gti
278         self.ncounts = len(self.time)
/soft/anaconda3/envs/3point8/lib/python3.8/site-packages/stingray/simulator/base.py in simulate_times(lc, use_spline)
64 …
```
=> Fix integer times in simulator

stingray/gti.py, stingray/io.py, stingray/pulse/fftfit.py
Normalize the shift before calculating the error bar in fftfit
Do not fail if the expected ID column is missing (resolves an issue with Chandra data)
New function to test whether an extension contains GTI (allows to use GTI extensions with custom names)
=> Minor fixes

setup.cfg, stingray/events.py, stingray/tests/test_events.py
Modifies `EventList.apply_mask` so that we don't need to hard-code a list of attributes (e.g., `time`, `energy`, `pi`).
This is done by the method `EventList.array_attrs()` that lists the attributes with the same shape as `time`.
This way, the user can create new mission-dependent attributes (e.g. `detector_id`) and they will be filtered by `apply_mask` automagically.
Also, this PR extends this to the roundtrip to `Table` and `Timeseries`, encoding the array attributes into table columns and vice-versa.
Finally, I add a new function to filter event lists by energy, which is very handy.
=> Better treatment of array-like attributes in eventlists

docs/intro.rst, setup.cfg, stingray/events.py, stingray/gti.py, stingray/lightcurve.py, stingray/simulator/base.py, stingray/tests/test_events.py, stingray/tests/test_gti.py, stingray/tests/test_lightcurve.py, stingray/tests/test_powerspectrum.py, stingray/utils.py
This PR improves by a lot the performance with the following GTI operations, by avoiding operations on the full time array:
+ `gti_border_bins`
+ `bin_intervals_from_gtis`
Also in this PR, new GTI operations:
+ `get_gti_lengths`: list the length of each GTI
+ `get_total_gti_length`: get the total observing time
+ `get_gti_events_idx`: get the first and the last bin of the `time` array in each GTI
Moreover:
+ Fix `Lightcurve.make_lightcurve` when the number of bins is close to the next integer (>=N + 0.99)
+ Add the new GTI machinery to EventList when creating light curve iterables; give both an iterator (`EventList.to_lc_iter`) and a list (`EventList.to_lc_list`)
=> Improve performance of existing GTI operations; add new GTI operations

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
=> Fix missing errorbars and err_dist in sliced light curves

CONTRIBUTING.md
Replaced 'master' in this contributing doc with 'main, to keep it consistent with the codebase.
=> Replace 'master' with 'main'

docs/install.rst
Pointing to link of actual docs, reference sphinx-astropy. Fixes issue https://github.com/StingraySoftware/stingray/issues/581
=> Fixing readthedocs ref

codecov.yml
Adjusts codecov settings, following up on issue https://github.com/StingraySoftware/stingray/issues/573. This should make it less aggressive, though still thoroughly checking the code and reporting back in a useful way. Now, codecov will NOT email you ever, and it will comment on the pull request after 7 (out of 9) continuous integration (CI) tests have completed. This should stop it from quickly emailing a contributor saying their code contribution has decreased coverage by 50%, as it was erroneously doing pretty often.
Resolve #573
=> Adjust codecov settings with new yaml file

.github/workflows/publish_docs.yml
So that we pick up any new version numbers, etc, in the published docs.
=> Run the publish_docs workflow on release

stingray/crosscorrelation.py, stingray/tests/test_crosscorrelation.py
The reason why the previous code did not provide zero time_shift for cross-correlation between two identical light curves of even length is as follows:
The correlation lags (x_legs) required to calculate time_shift was obtained by creating a linear space in cal_timeshift method.
The following line stores possible correlation lags in x_lags. 
`x_lags = np.linspace(-dur, dur, self.n)`  
The correlation lags obtained using this method depend on the evenness/oddity of self.n (i.e. number of time bins in the light curve).  For an odd number of time bins, np.linspace,  will provide an ndarray of integers centered at 0, but for an even number of time bins, it will generate an ndarray of floats which will not include 0. As a result, the time_shift will never be 0.
The correlation lags (x_legs) …
=> Bugfix for issue- CrossCorrelation Gives Strange Results (#592)

stingray/pulse/search.py
With reference to #667 and other similar issues reported over the years, I think it is just better to give segment_size an infinite default value, and only people who know what they are doing can set it to a lower value. Giving 5000 as a default value does not make sense
=> Change confusing default value of segment_size

stingray/io.py
Some NICER light curves have fractional exposure $\gtrsim$1, by a very small amount. An overly restrictive filter in the light curve reading made all these points invalid. Eliminating the filter
=> Fix issue with fracexp >~ 1

stingray/lightcurve.py, stingray/tests/test_lightcurve.py
Don't crash if fmt is None; use gti to define tstart and tseg if gti is defined
=> Fixes in Lightcurve

docs/contributing.rst
The Heroku application does not work anymore, this link is less pretty but it should work.
Thanks @bsipocz for reporting the bug
=> Update Slack link

stingray/crossspectrum.py, stingray/tests/test_crossspectrum.py
Addressing #612 , this Pr makes changes to the `crossspectrum.plot` feature, by adding object oriented matplotlib interface, which returns a `matplotlib.pyplot.axes` object when `axes` is not None and, plots a direct plot (retaining its original features) when called without giving an axes object.
I have created a test which checks that a new figure has been made. I have also tested the code with black and flake8.
=> Added oops plots and resolved errors

CONTRIBUTING.md, docs/changes/721.doc.rst, docs/contributing.rst, docs/install.rst
Information was spread in non-intuitive places. Here it is
=> Update docs with developer information

docs/changes/730.feature.rst, stingray/lightcurve.py, stingray/tests/test_lightcurve.py, stingray/utils.py
=> Check if invalid data are inside gtis, and warn or raise exception accordingly

docs/changes/736.bugfix.rst, stingray/conftest.py, stingray/fourier.py, stingray/modeling/tests/test_parameterestimation.py, stingray/powerspectrum.py, stingray/tests/test_powerspectrum.py
Also, it checks the last frequency allowed to compute rms 
Add tests
=> Prevent nan in the rms calculation

stingray/tests/test_events.py
Some test runs gave a different ordering in the energy array when the time arrays one sorted on contained repeated entries. 
E.g.:
```
time = [2, 1, 1]
energy = [5, 3, 4]
```
could result in `energy` being either `[3, 4, 5]` or `[4, 3, 5]` after sorting the event list.
This made some tests fail, probably due to some small recent change in Numpy sorting algorithms.
This fixes it, eliminating repeated entries and giving predictable results for the sorting.
=> Fix non-predictable ordering of test results

.github/workflows/ci_test.yml
In #743, I confused the non-starting of the standard build with the effect of "skip ci". Instead, the configuration file was wrong.
This fixes the issue. Still need to find a way to just start a docs build.
=> Fix failing test configuration

docs/changes/747.bugfix.rst, stingray/crossspectrum.py
Removed erroneous absolution of crossspectrum values in plot function.
=> Removal of unintended absolute plots of real and imaginary parts in crossspectrum

docs/changes/745.feature.rst, stingray/lightcurve.py, stingray/tests/test_lightcurve.py
Resolve #744 
Would something like this work for us? After all, I think it might make sense to have empty light curves, exactly like it makes sense, sometimes, to have empty event lists.
=> Allow empty lightcurves

.github/workflows/ci_test.yml
This should fix the failures with the check_commit step from forks
(E.g. #737 and #739)
=> Fix failure with external forks

docs/changes/753.bugfix.rst, stingray/lightcurve.py, stingray/tests/test_lightcurve.py
=> Update tstart and tseg when using Lightcurve.truncate()

docs/changes/756.bugfix.rst, stingray/events.py
Reduced memory usage of `from_lc` method of EventList by changing list comprehension to a generator comprehension expression
=> Reduced memory usage of EventList.from_lc()

docs/changes/757.trivial.rst, setup.cfg, stingray/events.py
Working further on #756, I came up with a faster way to allocate an event list from a list of counts.
Here I compare the performance of the two methods used now (using an iterator) and before #756 (using a list) with two new methods. One using simple numpy array, preallocated, and the other using Numba to further cut on loop execution speed.
```
In [1]: from numba import njit
...: from stingray import Lightcurve, EventList
...: import numpy as np
...: 
...: def from_lc(lc):
...:         # Multiply times by number of counts
...:         times = ([i] * int(j) for i, j in zip(lc.time, lc.counts))
...:         # Concatenate all lists
...:         times = list(i for j in times for i in j)
...: 
...:         return EventList(time=times, gti=lc.gti)
...: 
...: def from_lc_list(lc):
...: …
```
=> Speedup from_lc further

.github/workflows/ci_test.yml, pyproject.toml, stingray/deadtime/tests/test_fad.py, stingray/deadtime/tests/test_models.py, stingray/modeling/tests/test_parameterestimation.py, stingray/modeling/tests/test_posterior.py, stingray/pulse/overlapandsave/test_ols.py, stingray/pulse/tests/test_accelsearch.py, stingray/pulse/tests/test_pulse.py, stingray/pulse/tests/test_search.py, stingray/simulator/tests/test_simulator.py, stingray/tests/test_bexvar.py, stingray/tests/test_bispectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_io.py, stingray/tests/test_lightcurve.py, stingray/tests/test_multitaper.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_spectroscopy.py, stingray/tests/test_utils.py, stingray/tests/test_varenergyspectrum.py
@pupperemeritus taught me that there is a nice option in `pytest`, that allows to mark tests as slow and avoid their execution. Here, I'm separating the execution of quick tests from the slow ones, in two ways:
+ By marking single tests with `@pytest.mark.slow`
+ By marking whole test modules with `pytestmark = pytest.mark.slow`.
To execute only the slow tests, it's sufficient to use the options `--run-slow -m` (the first option comes from `pytest-astropy`)
This way, we can execute only unmarked tests in most test suites, and leave only one/two with the full tests. This can give much quicker feedback if a PR breaks something.
=> Separate slow tests from quick ones

docs/changes/760.bugfix.rst, stingray/fourier.py, stingray/tests/test_fourier.py
Resolves two recently reported issues:
+ `avg_*s_from_event` methods not accepting complex fluxes and
+ `avg_*s_from_event` methods throwing errors of "no segment shorter than gti"
The first one comes from our forcing a float casting on input fluxes (to avoid integers - that can lead to casting errors in Numba routines, and quadruple precision, which is overkill), that kills complex numbers.
The second one comes from our re-defining `dt` to accommodate an exact number of bins inside a segment. This works well with actual events, but does damage when you have a light curve that was sampled with a given dt.
=> Fix powerspectrum from lightcurve - wrong size, float casting

docs/changes/737.feature.rst, docs/core.rst, docs/dataexplo.rst, docs/index.rst, stingray/__init__.py, stingray/fourier.py, stingray/lightcurve.py, stingray/lombscargle.py, stingray/tests/test_fourier.py, stingray/tests/test_lombscargle.py
This is a work in progress. Feel free to provide critique and suggestions for any bugs that may be or incorrect behaviour. So far I have implemented the base Lomb-Scargle Cross Spectrum and Power Spectrum classes. Do mention any useful statistical functions that may be of interest to people dealing with unevenly sampled data. I have so far only completed the slow implementation. As I work on the fast implementation, tests, statistical functions and documentation, I will tack on commits to this PR as i progress.
=> Astronomy Using Unevenly Sampled Data : GSoC 2023

docs/changes/762.bugfix.rst, stingray/crossspectrum.py, stingray/modeling/gpmodeling.py, stingray/simulator/tests/test_simulator.py, stingray/tests/test_crossspectrum.py
For some reason, in `Crossspectrum` the power type remained "real", which also meant that, by default, the lags measured by `Crossspectrum` were all wrong.
=> Fix crossspectrum all default

docs/changes/763.bugfix.rst, setup.cfg, stingray/crossspectrum.py, stingray/modeling/tests/test_gpmodeling.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py
Eliminates the annoying "imaginary" curve in Powerspectrum and other derivates of Crossspectrum that don't have one. Also, fixes the labels
=> Fix cross spectrum plotting

docs/changes/764.feature.rst, stingray/tests/test_utils.py, stingray/utils.py
Allow our fast histograms to accept weights. Also, uniformize the interface so that we have the same options across all 1d, 2d, 3d, and nd histograms. Use a single function to fail safe to the numpy implementation of each kind of histogram when Numba throws a typing error.
Breaking change: the option for data range is now `range` like in Numpy. It made no sense to have a different name for the different implementations.
=> Weighted histograms

.readthedocs.yaml
We had an issue with the docs build, which did not include the notebooks. This fixes it.
=> Update submodules before building docs

stingray/_astropy_init.py, stingray/modeling/parameterestimation.py, stingray/modeling/tests/test_parameterestimation.py
Sorry I did not catch this before.
This needed to be done since 2021. To solve the problem, I'm following the example of all other Astropy affiliated packages
https://github.com/astropy/regions/pull/338/files
=> Eliminate calls to old deprecated (and now, eliminated) astropy functions

README.rst
Currently, multiple doc links in the readme file are redirecting to a 404 page. This PR should fix these links.
=> Update doc links in readme.rst

docs/changes/776.bugfix.rst, stingray/crossspectrum.py
Fixed subcs duplication by adding a check in the for loop that copies the attributes from table's meta items. Addressing issue #773
=> Fixed subcs duplication

docs/changes/779.bugfix.rst, setup.cfg, stingray/crossspectrum.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py
+ Improves performance and consistency when using events (uses the internals already tested in `AveragePowerspectrum` to create light curves dynamically for each segment, rather than allocating the full light curve on the spot)
+ Resolves a bug when rebinning in time (it relied on dt, which was calculated in a weird manner)
+ Makes tests a little more understandable, I hope
BONUS: added Dynamical Cross spectrum, because why not
=> Fixes to dynamical power spectrum + Dynamical Cross spectrum

docs/index.rst, docs/timeseries.rst, stingray/__init__.py, stingray/base.py, stingray/crossspectrum.py, stingray/events.py, stingray/gti.py, stingray/io.py, stingray/lightcurve.py, stingray/powerspectrum.py, stingray/tests/test_base.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_events.py, stingray/tests/test_lightcurve.py, stingray/tests/test_lombscargle.py, stingray/tests/test_powerspectrum.py, stingray/utils.py, stingray/varenergyspectrum.py
An attempt at more general time series objects. Not taking for granted counts or count rates, having multiple array attributes, etc.
It might be, for example, spectroscopic or polarimetric light curves with multiple measurements per time point
Documentation for these changes can be found at https://github.com/StingraySoftware/notebooks/pull/73
~(Depends on #774)~ Merged
=> Generalized lightcurves

docs/changes/787.trivial.rst, setup.cfg, stingray/io.py, stingray/tests/test_io.py
Responding to an issue by G.L. Israel, I substituted a generic exception with a full traceback of what goes wrong when GTIs are not correctly read.
=> More informative GTI failure

docs/changes/782.feature.rst, docs/index.rst, stingray/base.py, stingray/lightcurve.py, stingray/pulse/overlapandsave/ols.py, stingray/tests/test_base.py, stingray/tests/test_lightcurve.py, stingray/utils.py
~Depends on #754~
Changes can be seen in action in https://github.com/StingraySoftware/notebooks/pull/76 
Also, resolve #612
=> Fill bad time intervals with fake data

docs/api.rst, docs/changes/780.feature.rst, docs/changes/782.feature.rst, docs/changes/787.trivial.rst, docs/index.rst, setup.cfg, stingray/base.py, stingray/crossspectrum.py, stingray/fourier.py, stingray/io.py, stingray/lightcurve.py, stingray/powerspectrum.py, stingray/pulse/overlapandsave/ols.py, stingray/tests/test_base.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_fourier.py, stingray/tests/test_io.py, stingray/tests/test_lightcurve.py, stingray/tests/test_powerspectrum.py, stingray/utils.py
This PR introduces Power colors à la Heil et al. 2015. Now we can calculate *power colors* (both linear and logarithmic) and the *hue*, also defined according to the same paper by Heil+. I added the relevant functions in `fourier.py`, and tested them in `test_fourier.py`
Moreover, Power colors can be directly calculated from the spectra in a `DynamicalCrossspectrum` or `DynamicalPowerspectrum`, with the new methods `power_colors`.
In order to make power colors more usable, we also needed a  simple way to combine contiguous power spectra to improve the S/N. I added a function to `DynamicalCrossspectrum` to combine n contiguous spectra together, regardless of their distance in time (e.g. two intervals on the opposite side of an occultation in NICER).
Demonstration here: …
=> Introduce power colors

docs/changes/781.feature.rst, stingray/base.py, stingray/events.py, stingray/lightcurve.py, stingray/tests/test_base.py, stingray/tests/test_events.py, stingray/tests/test_lightcurve.py
=> Colors (as in color-color or hardness-intensity diagrams)

docs/changes/789.bugfix.rst, stingray/varenergyspectrum.py
Resolve #741 
We had a bug in the calculation of the Poisson noise level, which was highly overestimated. This produced some wrong results in the error calculation.
=> Fix issue with Poisson noise in lag spectra

docs/changes/792.bugfix.rst, stingray/crossspectrum.py, stingray/deadtime/fad.py, stingray/deadtime/tests/test_fad.py, stingray/fourier.py, stingray/multitaper.py, stingray/powerspectrum.py, stingray/tests/test_covariancespectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_fourier.py, stingray/tests/test_io.py, stingray/tests/test_lightcurve.py, stingray/tests/test_multitaper.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_stats.py
I also had to fix a couple of things related to warnings, because the new pytest is much pickier. All the changes to warnings (and to imports in the top of files) are due to that. Please ignore for the sake of this PR. Only consider changes to (test_)crossspectrum, powerspectrum, fourier, and minor related changes in multitaper, lombscargle and deadtime.
Resolve #790
=> Fix compute rms

docs/changes/799.removal.rst, docs/conf.py, setup.py, stingray/__init__.py, stingray/base.py, stingray/deadtime/fad.py, stingray/deadtime/model.py, stingray/events.py, stingray/filters.py, stingray/gti.py, stingray/io.py, stingray/lightcurve.py, stingray/loggingconfig.py, stingray/modeling/parameterestimation.py, stingray/modeling/tests/test_parameterestimation.py, stingray/pulse/accelsearch.py
Encapsulated the logging setup in a function in a separate file(loggingconfig.py), then called this function from different files where logging is needed.
=> Eliminated the usage of astropy logging

CHANGELOG.rst, setup.cfg, stingray/crossspectrum.py, stingray/fourier.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_fourier.py, stingray/tests/test_powerspectrum.py, stingray/utils.py, stingray/varenergyspectrum.py
Resolve #663
Note for reviewers: I created a test reproducing exactly the MWE by @dhuppenkothen in #663, and a similar one for cross spectra. My first solution broke other tests, so I changed slightly the logic in `fourier.py` and `crossspectrum.py` to make everything work. 
In particular, if a segment size is almost an integer number of light curve bins (less than 1% away), instead of approximating to the lower bin I approximate to the higher one. Not more than that, because a bin with a significantly lower flux could alter the statistical properties of the data. New function in `utils.py` for this
=> Fix problem with single power spectrum

stingray/base.py, stingray/tests/test_base.py
In `StingrayTimeseries.fill_bad_time_intervals`, when the buffer size is small and count rates are low, there was the possibility that the count rate estimation failed with a numpy error. E.g., the test `test_no_counts_in_buffer` I added failed. Here, I catch the condition and warn that this is happening. Also, I made the estimation more robust when only one of the GTIs on the side of the bad time intervals has good data.
=> Fix count rate estimation error for particularly bad GTIs

docs/changes/808.feature.rst, stingray/base.py, stingray/events.py, stingray/fourier.py, stingray/gti.py, stingray/lightcurve.py, stingray/tests/test_base.py, stingray/tests/test_events.py, stingray/tests/test_lombscargle.py
In `generate_indices_of_segment_boundaries_unbinned`:
=> Speed up fourier py

docs/changes/814.bugfix.rst, stingray/base.py, stingray/tests/test_base.py
=> Fix property setting from astropy

docs/changes/800.trivial.rst, docs/deadtime.rst, stingray/crossspectrum.py, stingray/deadtime/model.py, stingray/deadtime/tests/test_models.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_powerspectrum.py, stingray/tests/test_utils.py, stingray/utils.py
The dead time model had a few issues: 
+ the sum of many values below computer precision which produced large errors in the final result -> I set a limit for new additions so that numbers get only added when larger than `10**(-np.finfo(float).precision)`
+ `check_A` and `check_B` had useless axes in some conditions due to the large dynamic range of values -> I changed them to "symlog" to allow for negative numbers with small powers of ten.
I also added a trend line that estimates the estimated floating point error propagation after using the Bks for the actual calculation
Also in this PR: 
+ Added the possibility of calculating `B` and `A` for ranges of the parameter `k`
+ Added a new functions that calculates the deadtime-distorted PDS with more user-friendly parameters (e.g. providing …
=> Fix deadtime model

.github/ISSUE_TEMPLATE/Issue.yml, .github/ISSUE_TEMPLATE/bug_issue.yml, .github/ISSUE_TEMPLATE/doc_Issue.yml, .github/PULL_REQUEST_TEMPLATE.md
fixes: #810 
Added templates for :
-BUG issues
-Documentation Issues
-Generic Issues
=> Added templates

docs/changes/824.bugfix.rst, stingray/base.py, stingray/events.py, stingray/fourier.py, stingray/gti.py, stingray/io.py, stingray/lightcurve.py, stingray/modeling/gpmodeling.py, stingray/modeling/parameterestimation.py, stingray/modeling/tests/test_parameterestimation.py, stingray/modeling/tests/test_scripts.py, stingray/power_colors.py, stingray/pulse/accelsearch.py, stingray/pulse/modeling.py, stingray/pulse/pulsar.py, stingray/pulse/search.py, stingray/simulator/base.py, stingray/simulator/transfer.py, stingray/spectroscopy.py, stingray/tests/test_base.py, stingray/tests/test_events.py, stingray/tests/test_fourier.py, stingray/tests/test_gti.py, stingray/tests/test_lightcurve.py, stingray/tests/test_power_colors.py, stingray/tests/test_varenergyspectrum.py, stingray/utils.py, stingray/varenergyspectrum.py
This PR substitutes all calls to `np.asarray` with `np.asanyarray`, which passes all subclasses of `np.ndarray` (as, for example, `np.memmap`)
Resolve #823
=> Avoid copy in memory of memmaps

docs/changes/822.bugfix.rst, setup.cfg, stingray/base.py, stingray/events.py, stingray/tests/test_base.py, stingray/tests/test_events.py
This is a quick fix to #821
Resolve #821
=> Fix operation on segment when result is NaN

docs/acknowledgements.rst, docs/citing.rst, stingray/multitaper.py
A very easy one. The link timelabtechnologies.com is unreacheable, and I'm eliminating it from the docs (otherwise the linkcheck test fails)
Also, fix deprecation warning of numpy.trapz in numpy 2.0
=> [TST] Fix link in docs and deprecated function from numpy

docs/changes/837.bugfix.rst, stingray/pulse/pulsar.py, stingray/pulse/tests/test_search.py
**Issue:** fold_events accepts keywords and ignores them (#835)
I implemented a function to verify if the keywords passed to `fold_events` match the optional parameters.
I created a function called `validate_key_in_list`. This function takes two arguments: `key` and `optional_parameters_list`. It checks if the `key` is present in the `optional_parameters_list`. If the `key` is not found in the list, the user receives a warning. Additionally, I have included an optional `ValueError`, which is commented out for now.
**Note:** This is my first contribution to the project. 😊
=> fold_events keyword validation 

README.rst
As requested by @hamogu at https://github.com/pyOpenSci/software-submission/issues/201#issuecomment-2385481059
=> Add pyOpenSci review badge

docs/changes/849.feature.rst, docs/timeseries.rst, stingray/crossspectrum.py, stingray/fourier.py, stingray/lightcurve.py, stingray/powerspectrum.py, stingray/tests/test_crossspectrum.py, stingray/tests/test_fourier.py, stingray/tests/test_powerspectrum.py
Basic implementation of the shift-and-add technique from [Mendez+1998](https://iopscience.iop.org/article/10.1086/311600/pdf)
Guide for review: the basic mechanism is in `fourier.py`, the examples in the doctests should be self-explanatory. In`DynamicalCrossspectrum` and `DynamicalPowerspectrum`, I just wrap the same functionality in convenient methods that unpack the relevant information from the dynamical spectra and use the function in `fourier.py`.
Example: if a QPO is changing its frequency during our observation
we can think of tracing its maximum (e.g. with `dcs.trace_maximum()`, here I did it by hand):
and then applying shift_and_add to improve signal-to-noise and, maybe, detect a second QPO:
=> Shift and add

pyproject.toml
Having it as a runtime dependency is not needed, and it's breaking the hendrics feedstock. See here: https://github.com/conda-forge/hendrics-feedstock/pull/19
=> Remove setuptools from runtime dependencies

CHANGELOG.rst, docs/changes/748.docs.rst, docs/changes/828.feature.rst, docs/changes/834.feature.rst, docs/changes/837.bugfix.rst, docs/changes/842.trivial.rst, docs/changes/847.trivial.rst, docs/changes/849.feature.rst, docs/index.rst, docs/largedata.rst, stingray/events.py, stingray/fourier.py, stingray/gti.py, stingray/io.py, stingray/mission_support/missions.py, stingray/mission_support/rxte.py, stingray/mission_support/tests/test_mission_support.py, stingray/tests/test_gti.py, stingray/tests/test_io.py
Introduces a new FITS reader class, that lazy loads the data until a slice is required (in which case, the wanted StingrayTimeseries object is created).
=> Fits event lists

.gitignore, docs/changes/853.bugfix.rst, stingray/io.py, stingray/mission_support/rxte.py, stingray/mission_support/tests/test_mission_support.py
When defining the new FITSTimeseriesREader, I mistakenly changed the format of the `header` attribute of the output time series (from string to dictionary). This broke upstream code (HENDRICS, at least). I'm now fixing the issue.
Also, RXTE files sometimes do not contain the mission information in HDU0: we need to be robust to that (hence the cycling of hdus until MISSION or TELESCOP are found).
=> Fix header

joss/joss.bib, joss/paper.md
A few small editorial tweaks for the [JOSS publication](https://github.com/openjournals/joss-reviews/issues/7389). There are a few corrections to the paper but this is mostly to make the journal and article titles consistent in the references.
=> JOSS editorial tweaks

docs/changes/858.bugfix.rst, stingray/io.py, stingray/tests/test_io.py
=> Fix split at gtis

docs/changes/861.bugfix.rst, stingray/bispectrum.py
=> Fix toeplitz

docs/changes/863.feature.rst, stingray/io.py
This is a trivial addition: when present, the OBS_ID header keyword is read and added to the meta information of the `FitsTimeseriesReader` (and the `EventList` that will be created from it)
=> Add obsid info

docs/changes/865.feature.rst, stingray/crossspectrum.py, stingray/fourier.py, stingray/tests/test_crossspectrum.py
Solving a bug, and taking it as a starting point to resolve #864
=> Accounting for energy overlap in cross spectral products

docs/conf.py, docs/index.rst
Resolve #867 
Resolve #862
and other independent reports
We now specify that you need the source code version in order to run the tests with `tox` or build the documentation.
=> Update building and testing instructions

docs/changes/870.bugfix.rst, stingray/bexvar.py, stingray/pulse/accelsearch.py, stingray/pulse/tests/test_accelsearch.py
=> Fix arguments of Scipy special functions

README.rst, docs/index.rst, tox.ini
Fixes the recent linkcheck failures due to a change in the PyOpenSci github page
=> Fix linkcheck

docs/changes/922.bugfix.rst, docs/conf.py, pyproject.toml, stingray/stats.py
There was an error when calculating the upper limit on power in stingray.stats, when the number of summed powers is different from 1. Fixed
=> Fix power upper limit for n =/= 1

docs/changes/940.feature.rst, pyproject.toml, stingray/gti.py, stingray/io.py, stingray/mission_support/rxte.py, stingray/tests/test_events.py, stingray/utils.py
This small addition allows to use the power of `fits.open` to load remote datasets. See https://docs.astropy.org/en/latest/io/fits/index.html#working-with-remote-and-cloud-hosted-files
=> Allow loading of remote files, avoid extra loading of FITS files
