- README.rst
Added institute affiliations to Authors list, put lags and cross spectra on same line, mentioned pull requests and issues tracker at bottom.
> README changes

- stingray/lightcurve.py
- stingray/powerspectrum.py
- stingray/utils.py
Hi !
I ran [`pep8`](https://www.python.org/dev/peps/pep-0008/) over the modules and found some minor changes to be done. Please review the change. I ignored errors where the line was 80 chars long but pep8 wants it to be 79. I think there is no problem with 80 characters in a line.
> Minor code style fixes

- stingray/powerspectrum.py
- stingray/utils.py
This is the best way instead of adding a `.` to integers. Please review.
PS. We need to get travis working soon.
> Use float division from __future__

- stingray/io.py
- stingray/lightcurve.py
- stingray/powerspectrum.py
- stingray/pulse/pulsar.py
- stingray/pulse/tests/test_pulse.py
- stingray/tests/test_io.py
- stingray/tests/test_lightcurve.py
- stingray/tests/test_powerspectrum.py
- stingray/tests/test_utils.py
- stingray/utils.py
A bunch of small corrections to stop my linter to raise warnings about [pep8](https://www.python.org/dev/peps/pep-0008/) compliance
> Pep8 Corrections

- CREDITS.rst
- README.rst
- stingray/io.py
- stingray/lightcurve.py
- stingray/powerspectrum.py
- stingray/pulse/pulsar.py
- stingray/pulse/tests/test_pulse.py
- stingray/tests/test_io.py
- stingray/tests/test_lightcurve.py
- stingray/tests/test_powerspectrum.py
- stingray/tests/test_utils.py
- stingray/utils.py
As the project is becoming more complicated, and we want to give credit to those who contribute, I've moved the authors out of README.rst and instead made CREDITS.rst similar to what astropy does where contributors can add themselves before pull requests get accepted.
> Moved authors out of readme, added CREDITS.rst

- .travis.yml
- appveyor.yml
> Install matplotlib on travis and appveyor for tests

- stingray/lightcurve.py
- stingray/tests/test_lightcurve.py
Code added to make sure that the input time iterable is regularly
spaced, i.e. the bin sizes are equal throughout.
Solves #77
> stingray/lightcurve: Validated input time array

- stingray/io.py
- stingray/tests/test_utils.py
- stingray/utils.py
#Making private methods public
Adding some spaces between operators
Changing iterating way over dict
Solves: #86
> Utils.py - small refactor + make private methods public

- README.rst
Added installation section to Readme - regarding issue #84
> Added info about installation to Readme

- .travis.yml
- stingray/io.py
- stingray/lightcurve.py
- stingray/tests/test_io.py
- stingray/tests/test_lightcurve.py
We want to expand the Lightcurve class to add new features and properties to it. I have started with drawing feature.
Usage :
```python
>>> import matplotlib.pyplot as plt
>>> import stingray
>>> # Create time and counts array
>>> lc = stingray.Lightcurve(time, counts)
>>> lc.draw()
>>> plt.show()
```
> Refactor Lightcurve class and add more features

- stingray/simulator/events.py
- stingray/simulator/tests/test_events.py
This pull request deals with developing methods to add spectral information to event lists. Currently, the basic inverse transform method has been coded. Would be writing tests soon.
> Add spectral information to Event Lists

- stingray/crossspectrum.py
- stingray/powerspectrum.py
- stingray/tests/test_crossspectrum.py
Add a public function as well as a method of `Crossspectrum`.
Suggestions are most welcome, especially in docstrings. :)
> Add coherence function

- stingray/simulator/events.py
- stingray/simulator/models.py
- stingray/simulator/simulator.py
- stingray/simulator/tests/test_events.py
- stingray/simulator/tests/test_simulator.py
- stingray/simulator/utils.py
This PR starts to implement simulator class and will mainly cover to methods: 1) Light Curve generation from power spectrum, and 2) Light Curve generation from impulse responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/107)
> Implement Simulator Class

- .travis.yml
- appveyor.yml
- requirements.txt
- stingray/gti.py
- stingray/io.py
- stingray/lightcurve.py
- stingray/tests/test_gti.py
- stingray/tests/test_io.py
- stingray/tests/test_lightcurve.py
- stingray/tests/test_utils.py
- stingray/utils.py
Commits cherry-picked from #99 to resolve conflicts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/108)
> IO Functionalities

- stingray/crossspectrum.py
- stingray/powerspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
I refactored `Powerspectrum` to remove code duplicating functionality in `Crossspectrum`. I also fixed a bug in the  normalization of the `Crossspectrum`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/104)
> Refactored Powerspectrum class to use functionality in Crossspectrum

- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
Fixes `powerspectrum` tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/115)
> Simulator Fix

- stingray/crossspectrum.py
- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
Patch to fix problems created when I refactored `Powerspectrum`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/114)
> Fix simulator [WIP]

- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
This PR adds functionalities to simulate light curves using impulse response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/110)
> Impulse Reponse Simulator

- stingray/modeling/parameterestimation.py
- stingray/modeling/posterior.py
- stingray/modeling/tests/test_posterior.py
ps.ps is confusing. We changed it to ps.power
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/119)
> Change all ps.ps to ps.power

- stingray/modeling/parametricmodels.py
np.isinstance >> isinstance since it is built in in python, not numpy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/121)
> changed numpy stuff to regular python built in function:

- stingray/modeling/parameterestimation.py
t0 is a list of parameter values
ndim = **len(**t0**)**         from         ndim = t0
if emcee is successfully installed
can_**sample** = True        from         can_polt = True
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/123)
> Bugs for sampling with emcee fixed

- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
- stingray/simulator/utils.py
Corrects a few bugs in simulator channel functionalities, and implements read & write methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/124)
> Simulator functionalities

- stingray/events.py
- stingray/gti.py
- stingray/tests/test_events.py
- stingray/tests/test_gti.py
- stingray/utils.py
This PR:
- Corrects a few bugs that I discovered during testing.
- Adds a method in `events.py` to add event lists.
- Adds corresponding helper functions in `utils.py` and `gti.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/125)
> EventList Modifications

- stingray/events.py
- stingray/tests/test_events.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/134)
> Fixes #127: Allows join operation if one of the eventlists is empty

- README.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/133)
> A more explanatory introduction

- stingray/crossspectrum.py
- stingray/gti.py
@abigailStev I tried your notebook on this branch and it worked. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/136)
> Fix bug in AveragedCrossspectrum rebin method

- stingray/simulator/tests/test_simulator.py
Fixes #135 
I believe there's a typo in `test_simulator`. It would be nice if someone could check it at Issue #135 and either merge this or close if I'm wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/139)
> Fix a typo in stingray/simulator/tests/test_simulator.py

- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
(1) Converts assertion to exception when channel already exists
(2) Adds a function to fetch lightcurves from all channels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/143)
> Simulator Bug Fixes

- stingray/lightcurve.py
- stingray/simulator/tests/test_transfer.py
- stingray/simulator/transfer.py
(1) Shows matplotlib plots once they are created.
(2) Assigns default value to `dt` while creating impulse responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/142)
> TransferFunction Bug Fix

- stingray/events.py
- stingray/tests/test_events.py
- Refactors set_times and set_pha methods to `simulate_times` and `simulate_energies` to make them clear.
- Adds `from_lc` static method to load events from light curve
- Makes `read()` method static.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/146)
> Modifications in EventList

- stingray/simulator/tests/test_transfer.py
- stingray/simulator/transfer.py
Resolves some bugs in `TransferFunction` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/147)
> Transfer Function Fixes

- stingray/pulse/pulsar.py
- stingray/pulse/tests/test_pulse.py
A couple of bugs fixed in detection level and probability functions.
Test coveraged increased significantly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/149)
> Fix pulse + test coverage increase

- stingray/events.py
- stingray/tests/test_events.py
This adds many checks for consistency of the event lists to join and their attributes, and tries to understand how to best merge them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/148)
> More consistent treatment when joining one or more empty event lists

- stingray/crossspectrum.py
- stingray/tests/test_crossspectrum.py
Resolves Issue  #155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/156)
> Fix coherence normalization

- stingray/lightcurve.py
I was going through the codebase and I noticed this typo in one of the error messages :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/161)
> Fixed a typo in Lighcurve Class

- docs/conf.py
- docs/index.rst
- docs/simulator.rst
Adds documentation for simulator module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/176)
> [WIP]: Simulator Documentation

- README.rst
The link to the documentation should be found easily in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/171)
> WIP: Update README with documentation and Forum link

- stingray/modeling/scripts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/181)
> Fix docs of fit_powerspectrum

- stingray/lightcurve.py
- stingray/tests/test_lightcurve.py
Adds missing tests for baseline function, accounts for GTIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/185)
> Baseline of light curve improved

- stingray/gti.py
- stingray/tests/test_gti.py
From MaltPyNT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/188)
> Check that there are times inside GTIs in bin_intervals_from_gtis

- .travis.yml
- stingray/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stingraysoftware/stingray/198)
> URGENT: Fix failure in new Numpy (difference of boolean arrays)

- stingray/__init__.py
- stingray/crosscorrelation.py
- stingray/tests/test_crosscorrelation.py
- stingray/tests/test_lightcurve.py
Closes #172
Adds cross-correlation function for time series. Any normalization of data approach used in literature in welcomed to discuss, a simple method is to normalize data by subtracting mean and dividing by standard deviation before calculating cross-correlation. Some literature also divides correlation by length of input series.
> Cross Correlation

- stingray/simulator/simulator.py
- stingray/simulator/tests/test_simulator.py
Fixes issue reported by @ricardovb in DAVE
> Fix the simulator for an odd number of bins

- stingray/pulse/pulsar.py
- stingray/pulse/search.py
- stingray/pulse/tests/test_pulse.py
- stingray/pulse/tests/test_search.py
+ Add phaseogram;
+ Slight change in search_best_peaks
Note: I updated the notebook already: https://github.com/StingraySoftware/notebooks/pull/13
> More pulsar improvements

- stingray/pulse/modeling.py
- stingray/pulse/tests/test_modeling.py
These functions can be used to fit the periodograms obtained by epoch folding, using a Sinc or a Gaussian function.
TODO:
> Functions to fit the epoch folding periodograms

- stingray/bispectrum.py
- stingray/tests/test_bispectrum.py
Implementation of `Bispectrum` as a fourier transform of 3rd Order Cumulant (Triple AutoCorrelation). 
Results are verified from a matlab version of bispectrum code.
Further Addition(s):
1. lag window functions (Currently no window is applied) # #
> Bispectrum

- stingray/crossspectrum.py
- stingray/powerspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
> Specifying segment_size is now compulsory

- ah_bootstrap.py
- docs/simulator.rst
- ez_setup.py
- stingray/simulator/simulator.py
This is an automated update of the astropy-helpers submodule to v2.0.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
> Update astropy-helpers to v2.0.1

- stingray/pulse/modeling.py
- stingray/pulse/tests/test_modeling.py
This is needed to pickle and unpickle these objects correctly
> Add __reduce__ method to pickle/unpickle SincSquareModel

- stingray/modeling/posterior.py
- stingray/modeling/tests/test_posterior.py
I added the Laplace log-likelihood that's used for Cospectra, but I'm not 100% sure it's correct.
The Laplace likelihood is simple. The log-likelihood should just be
$P(x_i | m_i) = -log(2*\sigma_i) - |x_i - m_i|/\sigma_i$ 
for a data point $x_i$ and a parametric model value at that position $m_i$, and a data uncertainty $\sigma_i$. 
Unless I've missed something.
@matteobachetti Are there any (astronomy) references I can look up?
> Added Laplacian log-likelihood

- stingray/modeling/parameterestimation.py
- stingray/modeling/posterior.py
- stingray/modeling/tests/test_parameterestimation.py
Small bug fixes for modelling subpackage.
> Modelling small bugfixes

- stingray/utils.py
Eqs. B1-B3 of Vaughan+03, MNRAS, 345, 1271
> Fix the normalization of the error bars in Fvar and sigma_NXS

- stingray/pulse/pulsar.py
- stingray/pulse/search.py
- stingray/pulse/tests/test_pulse.py
- stingray/pulse/tests/test_search.py
* Fix failing z_n^2 test when nbin is not 16; test properly
* Solve bug when calculating orbital delays
> Fix psr search with zn

- stingray/crossspectrum.py
- stingray/pulse/search.py
- stingray/pulse/tests/test_search.py
Another branch got mixed up with this, but the changes should be straightforward to get.
One is applying GTIs before calculating cross spectra, the other is adding trial dot to epoch folding-like searches
> EF and Z search allow trial fdots

- stingray/covariancespectrum.py
> Removed spurious print statements

- stingray/lightcurve.py
@dhuppenkothen @matteobachetti
> Updated `plot()` to display the figure

- stingray/lightcurve.py
- stingray/utils.py
> Update utils.py documentation

- stingray/events.py
- stingray/pulse/pulsar.py
+ Fix an in-place summation that was modifying arrays upstream in a subtle way.
+ Don't forget about mjdref when joining event lists!
> Quick bug fixes

- .travis.yml
- requirements.txt
- Addresses issue #70 
- Requires assistance
- Took help from this [link](https://github.com/sunpy/sunpy/blob/master/requirements/base.txt)
- **Requires assistance**
> [WIP] Updated requirements

- docs/install.rst
This somehow doesn't build on my laptop, but I think it should work. :)
> Added conda installation to docs

- stingray/crosscorrelation.py
- stingray/crossspectrum.py
- stingray/tests/test_crossspectrum.py
This PR contains:
1. `plot` in `crossspectrum.py`
2. a fix in `crosscorrelation.py` (taken help from my previous fix(#300) in `lightcurve.py`
Credits go to the person who wrote `plot` function in other classes.
Is there any other class that is missing `plot`?
@matteobachetti @abigailStev
> Created new plot function in cross spectrum

- stingray/modeling/scripts.py
Following changes are included in this PR:
> Updated `starting_pars` parameter in scripts.py

- stingray/pulse/pulsar.py
A very basic operation that was missing. Should be *extremely* quick to review :)
> Add period to f conversion

- README.rst
- stingray/crossspectrum.py
- stingray/filters.py
- stingray/modeling/scripts.py
- stingray/modeling/tests/test_scripts.py
- stingray/spectroscopy.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_filters.py
- stingray/tests/test_spectroscopy.py
- stingray/tests/test_utils.py
- stingray/utils.py
This is a big merge that includes my work during GSoC 2018 coding period. (The lists will be updated frequently.)
This PR includes:
- Classes and Functions
- Documentation
- Unit tests
Following are new classes:
Following are new functions:
Resolves #293
> Add classes and functions for QPO spectroscopy

- stingray/_astropy_init.py
This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.
> Package-template update: _astropy_init.py

- joss/paper.md
> Whitespace fixes to YAML metadata for JOSS paper.

- stingray/crossspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
This is basically PR #388, except hopefully without merge conflicts?
@abigailStev: Can you try to check out this branch (not fork it), and then push to this PR directly?
> [WIP] Fix of bug in definition of absolute rms normalization of the PSD

- joss/paper.md
Added the reference to the accepted ApJ paper to the JOSS version
> Added ApJ reference

- joss/paper.md
Fixed co-authors to be the same as for the ApJ paper.
> Fixed co-authors

- joss/paper.md
> Fixing the paper compilation

- README.rst
- docs/install.rst
I added citation information to the readme and updated the installation instructions a little bit. Let's hope all the badges work!
> Add citation info

- stingray/gti.py
- stingray/tests/test_gti.py
It works also when multiple GTIs touch (Resolve #421 )
> New version of join_equal_gti_boundaries

- stingray/tests/test_crossspectrum.py
This should fix the error reported in #424
> Fixed typo in test_different_tseg

- .travis.yml
- stingray/modeling/parameterestimation.py
- stingray/modeling/tests/test_parameterestimation.py
- stingray/tests/test_crossspectrum.py
now with a bunch of fixes for the new emcee.
> Second attempt to fix travis

- stingray/crossspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
this PR implements the calculation of classical p-values comparing an outlier in a spectrum to white noise for the case of cospectra, as defined in [Huppenkothen & Bachetti, 2018](http://iopscience.iop.org/article/10.3847/1538-4365/aabe38/pdf).
> Cospectra significance

- stingray/tests/test_utils.py
- stingray/utils.py
I wrote a new function related to `assign_value_if_none` that applies a function if a variable is None, but only in that case, which should fix some of the timing issues? 
It might be worth thinking about whether we should do this in a function at all, or rather just implement if-else statements whereever that function is used, because function calls do have some computational overhead.
cc @matteobachetti
> Assign a function value if variable is None

- stingray/crossspectrum.py
- stingray/lightcurve.py
- stingray/powerspectrum.py
There were a few places where `dt` wasn't set or `skip_checks` wasn't defined, so I got lots of warning when trying to make PSDs. This should fix things.
> `dt` during summation missing

- stingray/pulse/accelsearch.py
- stingray/pulse/tests/test_accelsearch.py
Try to get the f-fdot from a lightcurve using the accelsearch method
> Accelsearch method

- stingray/crossspectrum.py
- stingray/powerspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
... and also adds it to the averaged cross spectrum class.
> Make progressbar optional

- docs/install.rst
- Adding instructions for installing dependencies
- Adding instructions for developer setup which might
help new contributors
> Improving installation instuctions for docs

- stingray/events.py
- stingray/gti.py
- stingray/lightcurve.py
- stingray/tests/test_events.py
- stingray/tests/test_lightcurve.py
- Resolve #466
- Fix bugs in change of MJDREF (old formula had the wrong sign!)
- Allow summing, joining and subtracting lcs with different mjdref
> Allow transparent MJDREF change

- setup.cfg
- stingray/lightcurve.py
- stingray/modeling/parameterestimation.py
Solves #478. Created a new attribute self.skip_checks. Inherited self.skip_checks attribute whenever a new lightcurve is created.
> Fixed skip_checks issue in Lightcurve

- stingray/lightcurve.py
- stingray/utils.py
@matteobachetti 
This PR aims at fixing #483 and is identical to #490
> Optimize counts_err function in Lightcurve

- stingray/lightcurve.py
- stingray/tests/test_lightcurve.py
> Optimize the Lightcurve.check_lightcurve function

- stingray/events.py
- stingray/io.py
- stingray/tests/test_events.py
@matteobachetti 
Solves #493. Added high_precision parameter.
Memory usage is negligible.
> Added high precision parameter for memory optimisation

- .travis.yml
- stingray/io.py
- stingray/tests/test_events.py
- stingray/utils.py
Resolve #504, and fix another yet unreported bug when normalizing the error bar.
> Fix two bugs in rebin_data

- .github/workflows/ci_test.yml
- setup.cfg
- stingray/pulse/tests/test_pulse.py
- stingray/stats.py
- stingray/tests/test_stats.py
- stingray/utils.py
- tox.ini
Add utility functions for statistics
Make them more stable by using the correct asymptotic approximations for the chi squared distribution 
Add significance estimate expressed in $\sigma$s!
> Better and more stable statistical functions

- stingray/lightcurve.py
- stingray/tests/test_lightcurve.py
> Accept Time or Quantity objects; fix docstring

- CONTRIBUTING.md
I deleted the earlier PR #472  due to a branch conflict. 
This version is updated to the Commit: 6f3f528
I have documented the Coding, Contribution, Testing and Community Guidelines and added them to CONTRIBUTING.md.
I took into consideration the answer in Issue #6 as well as stingray's CONTRIBUTING.md and the Astropy guidelines for the above-mentioned topics.
I was not really sure about the testing and community guidelines but I feel that there must be some additions in the same.
This documentation will help new contributors to get familiarised with our coding and contribution preferences. It will ensure uniformity in the codebase as well as the PR's and commits.
Hope this is helpful!! :)
> Added Coding, Contribution, Testing and Community Guidelines

- stingray/utils.py
> Fix test failures due to (I think) scipy using lists

- CHANGELOG.md
> Add draft changelog

- stingray/io.py
- stingray/tests/test_io.py
> Split numbers

- stingray/crossspectrum.py
- stingray/tests/test_utils.py
- stingray/utils.py
I have data where the time resolution changes halfway through (thank you, Fermi/GBM!) so I'm trying to figure out whether there's a way I can allow for variable bin-size in input data, with the idea that it would rebin correctly.
This seems to work.
> Rewrite of binning function to allow for variable resolution in input data

- stingray/deadtime/fad.py
- stingray/deadtime/tests/test_fad.py
- stingray/modeling/parameterestimation.py
- stingray/modeling/tests/test_parameterestimation.py
- stingray/powerspectrum.py
- stingray/pulse/accelsearch.py
- stingray/pulse/tests/test_modeling.py
- stingray/pulse/tests/test_pulse.py
- stingray/tests/test_io.py
- stingray/tests/test_lightcurve.py
- stingray/tests/test_powerspectrum.py
Stingray has a *lot* of warnings in the tests. This is a first pass at diagnosing and fixing some of them.
> Fix warnings in tests

- setup.cfg
- stingray/modeling/parameterestimation.py
- stingray/modeling/tests/test_parameterestimation.py
This makes the logging work correctly without duplication, and fixes minor issues due to API changes in emcee and matplotlib.
> Minor bug fixes in modelling

- stingray/lightcurve.py
> Fixes bug in analyze_by_chunks and estimate_chunk_length

- stingray/covariancespectrum.py
- stingray/crossspectrum.py
- stingray/deadtime/fad.py
- stingray/pulse/accelsearch.py
- stingray/tests/test_spectroscopy.py
FFTpack was everywhere. I thought we had eliminated it.
This should do.
Also, fixed a tiny bug in AveragedCovarianceSpectrum when band_interest was an array
> Purge fftpack everywhere

- README.rst
Fix a few glitches, update URLs to the new domain, shorten and remove duplication with the main documentation.
> Clean up README.rst

- CHANGELOG.rst
- stingray/crossspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_powerspectrum.py
Now also working with background-subtracted and/or Gaussian light curves!
~Already includes the changes from #542 . Will be WIP until that is merged~
Ready for review, with the need of small changes to the docs.
> New crossspectrum norm

- docs/deadtime.rst
> Fix doc formatting glitches

- .github/workflows/publish_docs.yml
- README.rst
> Publish docs to subdomain

- CHANGELOG.rst
> Update changelog for v0.3

- stingray/__init__.py
- stingray/multitaper.py
- stingray/tests/test_multitaper.py
This implementation uses `scipy` package, which is already a dependency, as opposed to the proof-of-concept implementation (#548 ) which used another external library.
This implementation contains the basic building blocks for the multitaper periodogram(#361 ) and some utility functions, either directly used from `Powerspectrum `or `Crossspectrum `class, or modified for this specific use case.
> Multitaper Periodogram using scipy

- stingray/crossspectrum.py
> Fix coherence uncertainty

- tox.ini
See APE-2: https://github.com/astropy/astropy-APEs/blob/main/APE2.rst
> Correct definition of Astropy LTS

- stingray/fourier.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_fourier.py
- stingray/tests/test_powerspectrum.py
Ooops.
This fixes a bug I just found with the new Fourier methods. My bad for missing this particular test that had to be done.
> Fix wrong normalization with common mean, and test at multiple levels

- stingray/simulator/simulator.py
> Make simulator errors all zero

- stingray/fourier.py
- stingray/tests/test_fourier.py
- tox.ini
> If the variance is zero, fail to Leahy-normalize

- stingray/crossspectrum.py
- stingray/fourier.py
- stingray/powerspectrum.py
- stingray/tests/test_crossspectrum.py
- stingray/tests/test_largememory.py
- stingray/tests/test_powerspectrum.py
> Use consistently new and legacy interface

- stingray/powerspectrum.py
- stingray/tests/test_powerspectrum.py
> Make modulation upper limit in PDS work with any normalization

- stingray/crosscorrelation.py
- stingray/tests/test_crosscorrelation.py
> Implement Gardner-Done normalization for Crosscorrelation

- stingray/powerspectrum.py
- stingray/tests/test_powerspectrum.py
> Accept input events in DynamicalPowerSpectrum

- stingray/pulse/pulsar.py
- stingray/pulse/tests/test_pulse.py
THIS WILL BREAK EXISTING CODE. Fixes issue https://github.com/StingraySoftware/stingray/issues/480.
> Replaced 'gtis' with 'gti' for consistent keyword use.

- .github/workflows/ci_test.yml
- stingray/simulator/tests/test_simulator.py
Verify that the issue from #404 is not relevant anymore
Resolve #404
> Verify that alternative uses of simulators give consistent results

- stingray/io.py
This solves a bug reported by @giallixx
> Fix PLEPHEM if it is a number instead of a string

- stingray/bispectrum.py
- stingray/crosscorrelation.py
- stingray/fourier.py
- stingray/multitaper.py
- stingray/pulse/accelsearch.py
- stingray/pulse/overlapandsave/test_ols.py
- stingray/spectroscopy.py
- stingray/tests/test_crosscorrelation.py
- stingray/tests/test_spectroscopy.py
- stingray/utils.py
> Avoid multiple FFTW warning by centralizing import

- CHANGELOG.rst
Structured changelog section for v1.0beta with TLDR at top, then New, then Improvements, then Bug Fixes.
> Update CHANGELOG for v1.0beta!

- stingray/gti.py
- stingray/lightcurve.py
- stingray/tests/test_lightcurve.py
Added `bexvar()` method in Lightcurve class and its relevant tests as a part of GSoC"22 project.
- Added three new parameters and attributes in the `Lightcurve` class: `bg_counts`, `bg_ratio`, `frac_exp`
- Added `bexvar()` method to find Bayesian excess variance of Stingray `Lightcurve` object
- Added relevant tests to test_lightcurve.py
> Add find_bexvar() method in Lightcurve class and its relevant tests - GSoC"22

- stingray/powerspectrum.py
- stingray/tests/test_powerspectrum.py
Added "abs" and "none" normalisation to compute_rms function.
> Add more normalisations and white_noise_offset in compute_rms

- .github/workflows/ci_test.yml
- .github/workflows/publish_docs.yml
To avoid deprecation warnings.
> Bump version of GitHub actions

- docs/changes/727.bugfix.rst
- stingray/events.py
- stingray/tests/test_events.py
> Fix event loading from files with no fmt keyword

- CHANGELOG.rst
- docs/changes/697.trivial.rst
- docs/changes/707.trivial.rst
- docs/changes/712.bugfix.rst
- docs/changes/715.trivial.rst
- docs/changes/716.feature.rst
- docs/changes/718.trivial.rst
- docs/changes/721.doc.rst
- docs/changes/723.feature.rst
- docs/changes/725.bugfix.rst
- docs/changes/727.bugfix.rst
- docs/changes/730.feature.rst
- docs/changes/731.trivial.rst
Working on branch `create_release_112`, this PR will check that all tests pass.
It's practically the current main, but without the breaking changes from PR #729
> Release 1.1.2

- CHANGELOG.rst
- docs/changes/697.trivial.rst
- docs/changes/707.trivial.rst
- docs/changes/712.bugfix.rst
- docs/changes/715.trivial.rst
- docs/changes/716.feature.rst
- docs/changes/718.trivial.rst
- docs/changes/721.doc.rst
- docs/changes/723.feature.rst
- docs/changes/725.bugfix.rst
- docs/changes/727.bugfix.rst
- docs/changes/730.feature.rst
- docs/changes/731.trivial.rst
Here is a new shiny changelog from towncrier, classifying all changes from release 1.1.2 in their own section!
> Fix changelog

- stingray/crossspectrum.py
> Fix link to Vaughan and Nowak

- docs/api.rst
- setup.cfg
> Add description of StingrayObject and StingrayTimeseries to docs

- .github/workflows/ci_test.yml
- codecov.yml
Can I get a fast review on this? This solves some problems with test coverage that @capy-on-caffeine and I are having
> Add codecov token

- .github/ISSUE_TEMPLATE/Issue.yml
- .github/ISSUE_TEMPLATE/bug_issue.yml
- .github/ISSUE_TEMPLATE/doc_Issue.yml
Minor
fixed the template for : " blank title"
NA
NA
> Removed "Title" from templates

- docs/changes/878.trivial.rst
- docs/index.rst
- docs/requirements.txt
Trivial version bump to solve vulnerability
> Bump jinja

- docs/changes/888.deprecation.rst
- docs/index.rst
- stingray/_astropy_init.py
This pull request is to address #883
> removing the deprecated TestRunner

- docs/changes/933.feature.rst
- pyproject.toml
- stingray/powerspectrum.py
- stingray/tests/test_powerspectrum.py
Technique implemented for [El Byad et al. 2025](https://arxiv.org/pdf/2505.16921)
Also Resolve #934
> Gti corrected power spectrum for long, gappy observations
